gcc -c ../common/src/hardfault_handler.c -I ../common/hdr/ -I ../inc/ -I ../hdr/
gcc -c ../common/src/irq_va108xx.c -I ../common/hdr/ -I ../inc/ -I ../hdr/
gcc -c ../common/src/system_va108xx.c -I ../common/hdr/ -I ../inc/ -I ../hdr/

gcc -c ../driver/src/driver.common.c -I ../driver/hdr/ -I ../inc/ -I ../hdr

gcc -c ../driver/src/gpio_drv_api.c -I ../driver/hdr/ -I ../inc/ -I ../hdr
gcc -c ../driver/src/gpio_va108xx.c -I ../driver/hdr/ -I ../inc/ -I ../hdr

gcc -c ../driver/src/i2c_drv_api.c -I ../driver/hdr/ -I ../inc/ -I ../hdr
gcc -c ../driver/src/i2c_va108xx.c -I ../driver/hdr/ -I ../inc/ -I ../hdr

gcc -c ../driver/src/spi_drv_api.c -I ../driver/hdr/ -I ../inc/ -I ../hdr
gcc -c ../driver/src/spi_va108xx.c -I ../driver/hdr/ -I ../inc/ -I ../hdr

gcc -c ../driver/src/uart_drv_api.c -I ../driver/hdr/ -I ../inc/ -I ../hdr
gcc -c ../driver/src/uart_va108xx.c -I ../driver/hdr/ -I ../inc/ -I ../hdr

gcc -c ../src/reb_timer.c -I ../driver/hdr/ -I ../inc/ -I ../hdr
gcc -c ../src/reb_max11619.c -I ../driver/hdr/ -I ../inc/ -I ../hdr
gcc -c ../src/reb_main.c -I ../driver/hdr/ -I ../inc/ -I ../hdr
gcc -c ../src/reb_log.c -I ../driver/hdr/ -I ../inc/ -I ../hdr
gcc -c ../src/reb_adt75.c -I ../driver/hdr/ -I ../inc/ -I ../hdr
gcc -c ../src/main.c -I ../driver/hdr/ -I ../inc/ -I ../hdr